apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smart-event-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mohammed-aymane-saber/Smart-Event-Collaboration-Platform.git'
    targetRevision: HEAD
    path: . # On reste à la racine
    directory:
      recurse: true # On va dans les sous-dossiers
      include: '{**/*.yaml,**/*.yml}' # <--- AJOUTE CECI : Filtre pour ne lire que le YAML
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
